language: objective-c
os: osx
osx_image: xcode8.3

branches:
  only:
    - develop
    - master

before_script:
  - export LANG=en_US.UTF-8

before_install:
  - brew update
  - brew install swiftlint || true

script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then fastlane test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then fastlane beta; fi
  - swiftlint

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Gigsterous'
