# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.0.0"
generated_fastfile_id "352c236c-b8b9-4696-8d5a-42b3a0694b0f"
default_platform :ios

lane :test do
    scan(
        scheme: "Gigsterous",
        device: "iPhone 7",
        clean: true,
        code_coverage: true
    )
end

lane :provision do
    produce(
        app_name: 'Gigsterous',
        language: 'English',
        app_version: '1.0.0',
        sku: ENV['SKU']
    )

    match(type: "development")
end

lane :beta do
    match(type: "development")

    # build your iOS app
    gym(
        scheme: "Gigsterous",
        output_name: "Gigsterous",
        output_directory: "./build",
        clean: true
    )

    # upload to Beta by Crashlytics
    crashlytics(
        api_token: ENV["CRASHLYTICS_TOKEN"],
        build_secret: ENV["CRASHLYTICS_SECRET"]
    )
end
